### ISSUE TITLE
Regex parser doesn't work if the export contains term metadata

### ISSUE THREAD

**Issue by nyordanov** [boonebgorges/wordpress-importer#2]
[This](https://github.com/boonebgorges/wordpress-importer/blob/3d9c2d3ad9c623641a44c7260afcd3a8d1d2e1b4/parsers.php#L462) expects that `<wp:term>...</wp:term>` is on one line. Perhaps it should be implemented similar to the code for `<item>` below?

**Comment by boonebgorges** [comment]
Thanks for the report - I'll review this, but it's likely that we can handle like `<item>`, since the terms can never be nested.
